/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frmFrame;

import frmFrame.ConDB;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class frmBanhang extends javax.swing.JFrame {

    /**
     * Creates new form frmBanhang
     */
    private dangnhap dn;
    public frmBanhang() {
        
        initComponents();
        khachhang.setLocationRelativeTo(null);
        dthemkh.setLocationRelativeTo(null);
        load_sanpham();
        masanpham.setEnabled(false);
        giaban.setEnabled(false);
        donvitinh.setEnabled(false);
        soluong.setEnabled(false);
        tensanpham.setEnabled(false);
        soluongnhap.setEnabled(false);
        xoa.setEnabled(false);
        them.setEnabled(false);
        nhaplai.setEnabled(false);
        thanhtoan.setEnabled(false);
        jLabel1.setForeground(Color.decode("#cccccc"));
        tenkh.setForeground(Color.decode("#cccccc"));
        jButton1.setEnabled(false);
        tichdiem.setEnabled(false);
        doidiem.setEnabled(false);
        ngayban.setEnabled(false);
        sohoadon.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
          @Override
          public void windowClosing(WindowEvent e) {
              NhanvienDAO.logLogout(dangnhap.id);
              System.exit(0); // Thoát chương trình
          }
        });
          Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            NhanvienDAO.logLogout(dangnhap.id);
        }));
        khong.setVisible(false);
        ngayban.setDate(new java.util.Date());
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select top 1 madon from donhang order by madon desc";
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                int i=rs.getInt("madon");
                sohoadon.setText(String.valueOf(i+1));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    String sdt="";
    String hoten="";
    int diem=0;
    private boolean ktratrungdt(String ma){
        boolean kq=false;
        try {
            con=ConDB.ketnoiDB();
            String sql="select * from khachhang where sdt='"+ma+"'";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            if(!rs.next()){
                kq=true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return kq;
    }
    private void load_taikhoan(){
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select * from khachhang";
            ResultSet rs= st.executeQuery(sql);
            tblkhachhang.removeAll();
            String[] tdb={"Số điện thoại", "Họ và Tên", "Điểm tích lũy"};
            DefaultTableModel model= new DefaultTableModel(tdb, 0);
            while(rs.next()){
                Vector v= new Vector();
                v.add(rs.getString("sdt"));
                v.add(rs.getString("hoten"));
                v.add(rs.getString("diem"));
                model.addRow(v);
            }
            tblkhachhang.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        khachhang = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        tkkhachhang = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        themkh = new javax.swing.JButton();
        chonkh = new javax.swing.JButton();
        thoatd = new javax.swing.JButton();
        dthemkh = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        btnthemkh = new javax.swing.JButton();
        grpdiem = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        masanpham = new javax.swing.JTextField();
        soluong = new javax.swing.JTextField();
        tensanpham = new javax.swing.JTextField();
        donvitinh = new javax.swing.JTextField();
        giaban = new javax.swing.JTextField();
        soluongnhap = new javax.swing.JTextField();
        thanhtien = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        them = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        nhaplai = new javax.swing.JButton();
        them3 = new javax.swing.JButton();
        thanhtoan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txttiemkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesanpham = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledonhang = new javax.swing.JTable();
        doidiem = new javax.swing.JRadioButton();
        tichdiem = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        tenkh = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tongtien = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        khong = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        sohoadon = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ngayban = new com.toedter.calendar.JDateChooser();

        khachhang.setResizable(false);
        khachhang.setSize(new java.awt.Dimension(712, 431));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tìm kiếm:");

        tkkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tkkhachhang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tkkhachhangKeyReleased(evt);
            }
        });

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhachhangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblkhachhang);

        themkh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themkh.setText("Thêm");
        themkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themkhActionPerformed(evt);
            }
        });

        chonkh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chonkh.setText("Xác nhận");
        chonkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonkhActionPerformed(evt);
            }
        });

        thoatd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thoatd.setText("Thoát");
        thoatd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout khachhangLayout = new javax.swing.GroupLayout(khachhang.getContentPane());
        khachhang.getContentPane().setLayout(khachhangLayout);
        khachhangLayout.setHorizontalGroup(
            khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(khachhangLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tkkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, khachhangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(themkh)
                        .addGap(18, 18, 18)
                        .addComponent(chonkh)
                        .addGap(18, 18, 18)
                        .addComponent(thoatd)))
                .addContainerGap())
        );
        khachhangLayout.setVerticalGroup(
            khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tkkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themkh)
                    .addComponent(chonkh)
                    .addComponent(thoatd))
                .addContainerGap())
        );

        dthemkh.setResizable(false);
        dthemkh.setSize(new java.awt.Dimension(712, 431));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thông tin Khách Hàng");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Họ tên");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Số điện thoại");

        txthoten.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setText("Thoát");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        btnthemkh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthemkh.setText("Xác nhận");
        btnthemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemkhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dthemkhLayout = new javax.swing.GroupLayout(dthemkh.getContentPane());
        dthemkh.getContentPane().setLayout(dthemkhLayout);
        dthemkhLayout.setHorizontalGroup(
            dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthemkhLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthoten)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(dthemkhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dthemkhLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnthemkh)
                        .addGap(18, 18, 18)
                        .addComponent(exit)))
                .addContainerGap())
        );
        dthemkhLayout.setVerticalGroup(
            dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dthemkhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(81, 81, 81)
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(dthemkhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(btnthemkh))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Đơn vị tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Giá bán:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Số lượng hiện có:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Số lượng nhập:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Thành tiền:");

        masanpham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        soluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tensanpham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        donvitinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        giaban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        soluongnhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soluongnhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                soluongnhapFocusLost(evt);
            }
        });
        soluongnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soluongnhapKeyReleased(evt);
            }
        });

        thanhtien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thanhtien.setText("......................................");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(24, 24, 24)
                        .addComponent(soluongnhap))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(giaban, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(donvitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(tensanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(masanpham)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soluong)))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(masanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(donvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soluongnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(thanhtien)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        them.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        xoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        nhaplai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nhaplai.setText("Nhập lại");
        nhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaplaiActionPerformed(evt);
            }
        });

        them3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        them3.setText("Thoát");
        them3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them3ActionPerformed(evt);
            }
        });

        thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        thanhtoan.setText("Thanh toán và in hóa đơn");
        thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(them3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(nhaplai))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoa)
                    .addComponent(them3))
                .addGap(18, 18, 18)
                .addComponent(thanhtoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tìm kiếm sản phẩm:");

        txttiemkiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttiemkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttiemkiemKeyReleased(evt);
            }
        });

        tablesanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablesanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesanpham);

        tabledonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledonhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledonhang);

        grpdiem.add(doidiem);
        doidiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doidiem.setText("Đổi điểm");
        doidiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doidiemActionPerformed(evt);
            }
        });

        grpdiem.add(tichdiem);
        tichdiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tichdiem.setText("Tích điểm");
        tichdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tichdiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("KH:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Chọn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Tích điểm hoặc đổi điểm");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        tenkh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenkh.setText("............................................");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Tổng tiền:");

        tongtien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tongtien.setText(".......................................");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("VNĐ");

        grpdiem.add(khong);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mã hóa đơn:");

        sohoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Ngày bán:");

        ngayban.setDateFormatString("dd/MM/yyyy");
        ngayban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tichdiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doidiem)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(khong))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tenkh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttiemkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tongtien)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngayban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(425, 425, 425))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txttiemkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(sohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(ngayban, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1)
                            .addComponent(tenkh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(khong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tichdiem)
                                .addComponent(doidiem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(tongtien)
                            .addComponent(jLabel17))))
                .addGap(0, 118, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    String tammasp;
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        String masp=masanpham.getText().trim();
        String tensp=tensanpham.getText().trim();
        String giab=giaban.getText().trim();
        String sl=soluong.getText().trim();
        String dvt=donvitinh.getText().trim();
        String slnhap=soluongnhap.getText().trim();
        int tt=Integer.parseInt(slnhap)*Integer.parseInt(giab);
        if(slnhap.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
            return;
        }
        try {
            con=ConDB.ketnoiDB();
            String sql = null;
            if(!ktratrung(masp)){
                sql="update giohang set thanhtien=thanhtien+'"+tt+"', soluongnhap=soluongnhap+'"+slnhap+"' where masp='"+masp+"'";
            }else{
                sql= "insert into giohang values('"+ masp +"', N'"+ tensp +"', '"+ giab +"', '"+ dvt +"', '"+ slnhap +"', '"+ tt +"')";
            }
            Statement st= con.createStatement();
            st.executeUpdate(sql);
            con.close();
            load_giohang();
            masanpham.setText("");
            tensanpham.setText("");
            giaban.setText("");
            soluong.setText("");
            donvitinh.setText("");
            soluongnhap.setText("");
            soluongnhap.setEnabled(false);
            thanhtien.setText("......................................");
            xoa.setEnabled(false);
            them.setEnabled(false);
            nhaplai.setEnabled(false);
            thanhtoan.setEnabled(true);
            load_tongtien();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_themActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
            try {
            con=ConDB.ketnoiDB();
            String sql="delete from giohang where masp='"+tammasp+"'";
            Statement st= con.createStatement();
            st.executeUpdate(sql);
            con.close();
            load_giohang();
            load_tongtien();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_xoaActionPerformed

    private void nhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaplaiActionPerformed
        soluongnhap.setText("");
        thanhtien.setText("......................................");
    }//GEN-LAST:event_nhaplaiActionPerformed

    private void them3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them3ActionPerformed

        String id=dangnhap.id;
        System.out.println(id);
        con=ConDB.ketnoiDB();
        System.out.println(id);
        try {
            String sql="Select * from quanly where maquanly='"+id+"'";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            if(rs.next()){
                dispose();
                new Dashboard().setVisible(true);
            }else{
                 String sql2="Select * from nhanvien where manhanvien='"+id+"'";
                Statement st2= con.createStatement();
                ResultSet rs2= st2.executeQuery(sql2);
                if(rs2.next()){
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION){
                    NhanvienDAO.logLogout(id);
                    System.exit(0);
                }     
            }else{
                    JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_them3ActionPerformed

    private void thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhtoanActionPerformed

        String tt=tongtien.getText().trim();
        if(jCheckBox1.isSelected()){
             if(sdt.equals("")){
            JOptionPane.showMessageDialog(dthemkh, "Vui lòng chọn khách hàng!");
            return;
        }
             if(tichdiem.isSelected()){
                 try {
            con=ConDB.ketnoiDB();
                int ttien=Integer.parseInt(tt);
                 int diemtl=diem+(ttien/1000);
                System.out.println(diemtl);
                Statement st5=con.createStatement();
            String sql5=String.format("update khachhang set hoten=N'%s', diem=%d where sdt= '%s'", 
                                    hoten, diemtl, sdt);
            st5.executeUpdate(sql5);
                     System.out.println("đổi điểm thành công");
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
             }
             if(doidiem.isSelected()){
                 try {
            con=ConDB.ketnoiDB();
                int ttien=Integer.parseInt(tt);
                 int diemtl=0;
                System.out.println(diemtl);
                Statement st5=con.createStatement();
            String sql5=String.format("update khachhang set hoten=N'%s', diem=%d where sdt= '%s'", 
                                    hoten, diemtl, sdt);
            st5.executeUpdate(sql5);
                     System.out.println("đổi điểm thành công");
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
             }
        }
        
        try {
            con=ConDB.ketnoiDB();
            Statement st= con.createStatement();
            String sqlid="Select top 1 madon from donhang order by madon desc";
            String sql= "insert into donhang(ngayban, tongtien, manhanvien) values("
                    + "getdate(),"
                    + "'"+tt+"',"
                    + "'"+dangnhap.id+"')";
            st.executeUpdate(sql);
            ResultSet rs= st.executeQuery(sqlid);
            int id=0;
            while(rs.next()){
                id=rs.getInt("madon");
            }      
            String sql2="insert into chitietdonhang(madon, masp, soluong, giaban, thanhtien) "
                    + "select '"+id+"', masp, soluongnhap, giaban, thanhtien from giohang";
            String sql3="delete from giohang";
            st.executeUpdate(sql2);
            JasperDesign jdesign=JRXmlLoader.load("D:\\NetBeansProjects\\quanlisieuthi\\src\\main\\java\\frmFrame\\report1.jrxml");
            String sqlbc="select tensp, ct.soluong, ct.giaban, ct.thanhtien, tongtien\n" +
                        "from chitietdonhang ct, donhang dh, sanpham sp\n" +
                        "where ct.madon=dh.madon and sp.masp=ct.masp and ct.madon='"+id+"'";
            JRDesignQuery updateQuery=new JRDesignQuery();
            updateQuery.setText(sqlbc);          
            jdesign.setQuery(updateQuery);
            JasperReport jreport=JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint=JasperFillManager.fillReport(jreport, null,con);
            JasperViewer.viewReport(jprint);
            st.executeUpdate(sql3);
            con.close();
            JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
            load_giohang();
            load_sanpham();
            thanhtoan.setEnabled(false);
            jCheckBox1.setSelected(false);
            tenkh.setText("............................................");
            jLabel1.setForeground(Color.decode("#cccccc"));
            tenkh.setForeground(Color.decode("#cccccc"));
            jButton1.setEnabled(false);
            tichdiem.setEnabled(false);
            doidiem.setEnabled(false);
            thanhtien.setText("......................................");
            tongtien.setText(".......................................");
            sdt="";
            hoten="";
            diem=0;
            khong.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        ngayban.setDate(new java.util.Date());
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select top 1 madon from donhang order by madon desc";
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                int i=rs.getInt("madon");
                sohoadon.setText(String.valueOf(i+1));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_thanhtoanActionPerformed

    private void txttiemkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttiemkiemKeyReleased
        String tk=txttiemkiem.getText().trim();
        try {
            con=ConDB.ketnoiDB();
            String sql="select * from sanpham where tensp like N'%"+tk+"%'";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            tablesanpham.removeAll();
            String[] tdb={"Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Số lượng", "Đơn vị tính"};
            DefaultTableModel model= new DefaultTableModel(tdb, 0);
            while(rs.next()){
                Vector v= new Vector();
                v.add(rs.getString("masp"));
                v.add(rs.getString("tensp"));
                v.add(rs.getString("giaban"));
                v.add(rs.getString("soluong"));
                v.add(rs.getString("donvitinh"));
                model.addRow(v);
            }
            tablesanpham.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txttiemkiemKeyReleased

    private void tablesanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesanphamMouseClicked
        int i=tablesanpham.getSelectedRow();
        DefaultTableModel tb= (DefaultTableModel) tablesanpham.getModel();
        masanpham.setText(tb.getValueAt(i, 0).toString());
        tensanpham.setText(tb.getValueAt(i, 1).toString());
        giaban.setText(tb.getValueAt(i, 2).toString());
        soluong.setText(tb.getValueAt(i, 3).toString());
        donvitinh.setText(tb.getValueAt(i, 4).toString());
        soluongnhap.setEnabled(true);
        xoa.setEnabled(false);
        them.setEnabled(true);
        nhaplai.setEnabled(true);
    }//GEN-LAST:event_tablesanphamMouseClicked

    private void soluongnhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soluongnhapKeyReleased
        String masp=masanpham.getText().trim();
        String giab=giaban.getText().trim();
        String slnhap=soluongnhap.getText().trim();
        if(!slnhap.equals("")){
            int tt=Integer.parseInt(slnhap)*Integer.parseInt(giab);
            thanhtien.setText(String.valueOf(tt));
        }else{
            thanhtien.setText("......................................");
        }
        String slhienco=soluong.getText().trim();
        String sln=soluongnhap.getText().trim();
        int sl1=Integer.parseInt(slhienco);
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select * from giohang where masp='"+masp+"'";
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                sl1=sl1-rs.getInt("soluongnhap");
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        int sl2=Integer.parseInt(sln);
        if (sl2>sl1 && !sln.equals("")){
            JOptionPane.showMessageDialog(this, "Không đủ hàng");
            soluongnhap.setText("");
            thanhtien.setText("......................................");
            return;
        }
    }//GEN-LAST:event_soluongnhapKeyReleased

    private void tabledonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledonhangMouseClicked
        int i=tabledonhang.getSelectedRow();
        DefaultTableModel tb= (DefaultTableModel) tabledonhang.getModel();
        tammasp=tb.getValueAt(i, 0).toString();
        soluongnhap.setEnabled(false);
        xoa.setEnabled(true);
        them.setEnabled(false);
        nhaplai.setEnabled(false);
    }//GEN-LAST:event_tabledonhangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        load_taikhoan();
        khachhang.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tkkhachhangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkkhachhangKeyReleased
         String tk=tkkhachhang.getText().trim(); 
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select * from khachhang where sdt like N'%"+tk+"%' or hoten like N'%"+tk+"%'";
            ResultSet rs= st.executeQuery(sql);
            tblkhachhang.removeAll();
            String[] tdb={"Số điện thoại", "Họ và Tên", "Điểm tích lũy"};
            DefaultTableModel model= new DefaultTableModel(tdb, 0);
            while(rs.next()){
                Vector v= new Vector();
                v.add(rs.getString("sdt"));
                v.add(rs.getString("hoten"));
                v.add(rs.getString("diem"));
                model.addRow(v);
            }
            tblkhachhang.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }                                       
    }//GEN-LAST:event_tkkhachhangKeyReleased

    private void thoatdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatdActionPerformed
        khachhang.setVisible(false);
    }//GEN-LAST:event_thoatdActionPerformed

    private void tblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhachhangMouseClicked
        int i=tblkhachhang.getSelectedRow();
        DefaultTableModel tb= (DefaultTableModel) tblkhachhang.getModel();
        sdt=tb.getValueAt(i, 0).toString();
        hoten=tb.getValueAt(i, 1).toString();
        diem=Integer.parseInt(tb.getValueAt(i, 2).toString());
    }//GEN-LAST:event_tblkhachhangMouseClicked

    private void chonkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonkhActionPerformed
        if(sdt.equals("")){
            JOptionPane.showMessageDialog(dthemkh, "Vui lòng chọn khách hàng!");
            return;
        }
        tenkh.setText(hoten);
        khachhang.setVisible(false);
    }//GEN-LAST:event_chonkhActionPerformed

    private void btnthemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemkhActionPerformed
       String ht=txthoten.getText().trim();
       String phone=this.phone.getText().trim();
       if (phone.equals("") || ht.equals("")) {
        JOptionPane.showMessageDialog(dthemkh, "Vui lòng nhập đủ thông tin!");
        return;
    }    
    int diem=0;
    if (!ktratrungdt(phone)) {
        JOptionPane.showMessageDialog(dthemkh, "Mã tài khoản này đã tồn tại");
        return;
    }   
    try {
        con = ConDB.ketnoiDB();
        String sql = String.format("INSERT INTO khachhang (sdt, hoten, diem) VALUES ('%s', N'%s', %d)", 
                                    phone, ht, diem);
        
        Statement st = con.createStatement();
        st.executeUpdate(sql);
        con.close();
        
        JOptionPane.showMessageDialog(dthemkh, "Thêm tài khoản thành công!");
        load_taikhoan();
        this.phone.setText("");
        txthoten.setText("");
        dthemkh.setVisible(false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(dthemkh, "Có lỗi xảy ra: " + e.getMessage());
    }
    }//GEN-LAST:event_btnthemkhActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dthemkh.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void themkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themkhActionPerformed
       dthemkh.setVisible(true);
    }//GEN-LAST:event_themkhActionPerformed

    private void soluongnhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_soluongnhapFocusLost

    }//GEN-LAST:event_soluongnhapFocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(!jCheckBox1.isSelected()){
           khong.setSelected(true);
           tenkh.setText("............................................");
          jLabel1.setForeground(Color.decode("#cccccc"));
          tenkh.setForeground(Color.decode("#cccccc"));
          jButton1.setEnabled(false);
          tichdiem.setEnabled(false);
          doidiem.setEnabled(false);
          sdt="";
            hoten="";
            diem=0;
            load_tongtien();
        }else{
          jLabel1.setForeground(Color.decode("#000000"));
          tenkh.setForeground(Color.decode("#000000"));
          jButton1.setEnabled(true);
          tichdiem.setEnabled(true);
          doidiem.setEnabled(true);
          load_tongtien();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void doidiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doidiemActionPerformed
          if(sdt.equals("")){
            JOptionPane.showMessageDialog(dthemkh, "Vui lòng chọn khách hàng!");
            khong.setSelected(true);
            return;
        }
        load_tongtien();
    }//GEN-LAST:event_doidiemActionPerformed

    private void tichdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tichdiemActionPerformed
         if(sdt.equals("")){
            JOptionPane.showMessageDialog(dthemkh, "Vui lòng chọn khách hàng!");
            khong.setSelected(true);
            return;
        }
        load_tongtien();
    }//GEN-LAST:event_tichdiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBanhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBanhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBanhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBanhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBanhang().setVisible(true);
            }
        });
    }
    private void load_sanpham(){
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select * from sanpham";
            ResultSet rs= st.executeQuery(sql);
            tablesanpham.removeAll();
            String[] tdb={"Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Số lượng", "Đơn vị tính"};
            DefaultTableModel model= new DefaultTableModel(tdb, 0);
            while(rs.next()){
                Vector v= new Vector();
                v.add(rs.getString("masp"));
                v.add(rs.getString("tensp"));
                v.add(rs.getString("giaban"));
                v.add(rs.getString("soluong"));
                v.add(rs.getString("donvitinh"));
                model.addRow(v);
            }
            tablesanpham.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void load_giohang(){
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select * from giohang";
            ResultSet rs= st.executeQuery(sql);
            tabledonhang.removeAll();
            String[] tdb={"Mã sản phẩm", "Tên sản phẩm", "Đơn vị tính", "Giá bán", "Số lượng", "Thành tiền"};
            DefaultTableModel model= new DefaultTableModel(tdb, 0);
            while(rs.next()){
                Vector v= new Vector();
                v.add(rs.getString("masp"));
                v.add(rs.getString("tensp"));
                v.add(rs.getString("donvitinh"));
                v.add(rs.getString("giaban"));
                v.add(rs.getString("soluongnhap"));
                v.add(rs.getString("thanhtien"));
                model.addRow(v);
            }
            tabledonhang.setModel(model);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private boolean ktratrung(String ma){
        boolean kq=false;
        try {
            con=ConDB.ketnoiDB();
            String sql="select * from giohang where masp='"+ma+"'";
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            if(!rs.next()){
                kq=true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return kq;
    }
    
    private void load_tongtien(){
        try {
            con=ConDB.ketnoiDB();
            Statement st=con.createStatement();
            String sql="Select sum(thanhtien) as tongtien from giohang";
            ResultSet rs= st.executeQuery(sql);        
            if(rs.next()){
                if(rs.getString("tongtien") == null){
                    tongtien.setText(".......................................");
                }else{
                    if(doidiem.isSelected()){
                        int tt=rs.getInt("tongtien");
                        tt=tt-(diem*10);
                        tongtien.setText(String.valueOf(tt));
                    }else{
                        tongtien.setText(rs.getString("tongtien"));
                    }
                }
            }   
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthemkh;
    private javax.swing.JButton chonkh;
    private javax.swing.JRadioButton doidiem;
    private javax.swing.JTextField donvitinh;
    private javax.swing.JDialog dthemkh;
    private javax.swing.JButton exit;
    private javax.swing.JTextField giaban;
    private javax.swing.ButtonGroup grpdiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog khachhang;
    private javax.swing.JRadioButton khong;
    private javax.swing.JTextField masanpham;
    private com.toedter.calendar.JDateChooser ngayban;
    private javax.swing.JButton nhaplai;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField sohoadon;
    private javax.swing.JTextField soluong;
    private javax.swing.JTextField soluongnhap;
    private javax.swing.JTable tabledonhang;
    private javax.swing.JTable tablesanpham;
    private javax.swing.JTable tblkhachhang;
    private javax.swing.JLabel tenkh;
    private javax.swing.JTextField tensanpham;
    private javax.swing.JLabel thanhtien;
    private javax.swing.JButton thanhtoan;
    private javax.swing.JButton them;
    private javax.swing.JButton them3;
    private javax.swing.JButton themkh;
    private javax.swing.JButton thoatd;
    private javax.swing.JRadioButton tichdiem;
    private javax.swing.JTextField tkkhachhang;
    private javax.swing.JLabel tongtien;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txttiemkiem;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
